### ISSUE TITLE
Build Error in Production Mode Windows

### ISSUE THREAD

**Issue by camilomartins** [studio-arrenberg/engels-briefe#118]
![IMG_6809](https://user-images.githubusercontent.com/66945701/140057321-7428c845-b375-4981-ac02-dbc807c1977e.jpeg)
![IMG_6807](https://user-images.githubusercontent.com/66945701/140057346-43325514-7838-4bda-8ed2-548e23262712.jpeg)
![IMG_6808](https://user-images.githubusercontent.com/66945701/140057368-968a02cc-9b82-47ea-96c2-ec6d9cd50632.jpeg)
![IMG_6806](https://user-images.githubusercontent.com/66945701/140057391-61f46ba5-5d3b-4149-b74a-cdc7aa0ad12e.jpeg)

New Build Error in Production
<img width="1241" alt="Bildschirmfoto 2021-11-07 um 22 46 28" src="https://user-images.githubusercontent.com/66945701/140663013-f35d5dae-af6d-40f3-8fc7-c881f1d0adac.png">

**Comment by j0hannr** [comment]
@camilomartins vorschläge...

### Error 1
```warning
Der Befehl "NODE_ENV" ist entweder falsch gescrieben oder konnte nicht gefunden werden.
```
**Lösung**
```js
// file ./package.json
"start": "NODE_ENV=production node server.js", // current
"start": "next start", // proposal
```
### Error 2
```warning
Cannot read property of '_nextBubbleNoFallback' of undefined
```

**Lösung 1**
```js
const bubbleNoFallback=!!query._nextBubbleNoFallback; // previous
const bubbleNoFallback=false; // changed to resolve the issue
```
**Lösung 2**
`Waveform` nicht mehr nutzen und anderen audio player nehemen ohne waveform.

**Comment by camilomartins** [comment]
Error was caused by an CSS Line Error. Is fixed now.

**Comment by chngjunjie** [comment]
Hi @camilomartins , how do you solve this issues ?
