### ISSUE TITLE
Build Error in Production Mode on Mac

### ISSUE THREAD

**Issue by camilomartins** [studio-arrenberg/engels-briefe#119]
<img width="1241" alt="Bildschirmfoto 2021-11-07 um 22 46 28" src="https://user-images.githubusercontent.com/66945701/140663191-1e0eb77a-81da-4e07-9d86-d8f1967b2223.png">

**Comment by j0hannr** [comment]
`special character` issue. Maybe check all red marked files...

**Comment by camilomartins** [comment]
Error in Global.CSS File. CSS Comment was not correctly opened, so there was just one `*/` instead of one correct Line starting and ending with `/* Just an Example comment */` the comment Tag.

The incorrect CSS comment caused the build error.
